DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.conf.urls import url

import django.contrib.auth.views
from django.views.generic.base import RedirectView

import app.forms
import app.views
from app  import views
# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
import app.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    # Examples:
    url(r'^admin/', include(admin.site.urls)),
   
    
    
    
    

    
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^$', app.views.home, name='home'),
    url(r'^edit_order/(?P<id>\d+)/$', app.views.edit_order, name='edit_order'),
    url(r'^orders/$', app.views.orders, name='orders'),
    url(r'^edit/(?P<id>\d+)/$', app.views.edit, name='edit'),
    url(r'^delete/(?P<id>\d+)/$', app.views.delete, name='delete'),
    url(r'^users/$', app.views.users, name='users'),
    url(r'^empty/$', app.views.empty, name='empty'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'newpost', app.views.newpost, name='newpost'),
    url(r'newgame', app.views.newgame, name='newgame'),
    url(r'^favicon\.ico$', favicon_view),
    url(r'registration$', app.views.registration, name='registration'),
    url(r'^blog/$', app.views.blog, name='blog'),
    url(r'^blog/(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^cart/',include('cart.urls', namespace = 'cart')),
    url(r'orders/',include('orders.urls', namespace = 'orders')),
    url(r'^', include('app.urls', namespace='app')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/urls.py
from django.conf.urls import url
 
from . import views
 
urlpatterns = ([ 
    url(r'^my_orders/$', views.my_orders, name='my_orders'),
    url(r'^game_list$', views.game_list, name='game_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.game_list, name='game_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.game_detail, name='game_detail'),
    
    ])

cart/urls.py
from django.conf.urls import url
 
from . import views
 
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<game_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<game_id>\d+)/$', views.cart_remove,
        name='cart_remove'), ]
 

orders/urls.py
from django.conf.urls import url
 
from . import views
 
urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    
              ]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from  django import forms
 
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
 
 
class CartAddGameForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int, label='Количество')
    update = forms.BooleanField(required=False, initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST
 
from app.models import Game
from .cart import Cart
from .forms import CartAddGameForm
# Create your views here.

@require_POST
def cart_add(request, game_id):
    cart = Cart(request)
    game = get_object_or_404(Game, id=game_id)
    form = CartAddGameForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(game=game, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, game_id):
    cart = Cart(request)
    game = get_object_or_404(Game, id=game_id)
    cart.remove(game)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddGameForm(
            initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "app/layout.html" %}
{% load static %}
 
{% block title %}
    Ваша корзина
{% endblock %}
 
{% block content %}
    <h1>Ваша корзина</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Изображение</th>
            <th>Игра</th>
            <th>Количество</th>
            <th>Убрать</th>
            <th>Цена</th>
            <th>Общая цена</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with game=item.game %}
                <tr class="tdcart">
                    <td>
                        <a href="{{ game.get_absolute_url }}">
                            <img style="width:200px" src="
                                    {% if game.image %}{{ game.image.url }}{% else %}{% static "shop/img/no_image.png" %}{% endif %}">
                        </a>
                    </td>
                    <td style="color:red; text-align:center; text-shadow:black 0px 0px 3px;">{{ game.name }}</td>
                    <td >
                       <form  action="{% url "cart:cart_add" game.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                           <br />
                            <input class="button" type="submit" value="Обновить">
                            {% csrf_token %}
                        </form>

                    </td;>
                    <td style="color:red; text-align:center; text-shadow:black 0px 0px 3px;">
                        <a href="{% url "cart:cart_remove" game.id %}">Убрать</a>
                    </td>
                    <td style="color:red; text-align:center; text-shadow:black 0px 0px 3px;" class="num">{{ item.price }} руб.</td>
                    <td style="color:red; text-align:center; text-shadow:black 0px 0px 3px;" class="num">{{ item.total_price }} руб.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <hr />
            <td style="color:red; text-align:center; text-shadow:black 0px 0px 3px;">Итого</td>
            <td colspan="4"></td>
            <td style="color:red; text-align:center; text-shadow:black 0px 0px 3px;" class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
        </tbody>
    </table>
    {% if user.is_authenticated  %}
         <p class="text-right">
            <a href="{% url "app:game_list" %}" class="button light">Продолжить покупки</a>
            <a href="{% url 'orders:order_create' %}" class="button">Оформить заказ</a>
        </p>
    {% else %} 
    <h3> Для оформления заказа необходимо авторизоваться</h3>
{% endif %}
{% endblock %}  

cart/templates/cart/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>