DjangoWebProject1/urls.py
"""
Definition of urls for DjangoWebProject1.
"""

from datetime import datetime
from django.conf.urls import url

import django.contrib.auth.views
from django.views.generic.base import RedirectView

import app.forms
import app.views
from app  import views
# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()
import app.views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)


urlpatterns = [
    # Examples:
    url(r'^admin/', include(admin.site.urls)),
   
    
    
    
    

    
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Войти',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),
    url(r'^$', app.views.home, name='home'),
    url(r'^edit_order/(?P<id>\d+)/$', app.views.edit_order, name='edit_order'),
    url(r'^orders/$', app.views.orders, name='orders'),
    url(r'^edit/(?P<id>\d+)/$', app.views.edit, name='edit'),
    url(r'^delete/(?P<id>\d+)/$', app.views.delete, name='delete'),
    url(r'^users/$', app.views.users, name='users'),
    url(r'^empty/$', app.views.empty, name='empty'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'newpost', app.views.newpost, name='newpost'),
    url(r'newgame', app.views.newgame, name='newgame'),
    url(r'^favicon\.ico$', favicon_view),
    url(r'registration$', app.views.registration, name='registration'),
    url(r'^blog/$', app.views.blog, name='blog'),
    url(r'^blog/(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^cart/',include('cart.urls', namespace = 'cart')),
    url(r'orders/',include('orders.urls', namespace = 'orders')),
    url(r'^', include('app.urls', namespace='app')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

app/urls.py
from django.conf.urls import url
 
from . import views
 
urlpatterns = ([ 
    url(r'^my_orders/$', views.my_orders, name='my_orders'),
    url(r'^game_list$', views.game_list, name='game_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.game_list, name='game_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.game_detail, name='game_detail'),
    
    ])

cart/urls.py
from django.conf.urls import url
 
from . import views
 
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<game_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<game_id>\d+)/$', views.cart_remove,
        name='cart_remove'), ]
 

orders/urls.py
from django.conf.urls import url
 
from . import views
 
urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    
              ]

orders/models.py
from django.db import models
from app.models import Game
from django.contrib.auth.models import User
 
# Create your models here.
 
 
class Order(models.Model):
    nickname= models.ForeignKey(User, on_delete=models.CASCADE, verbose_name = 'Покупатель')
    first_name = models.CharField(max_length=50, verbose_name = 'Фамилия')
    last_name = models.CharField(max_length=50, verbose_name = 'Имя')
    email = models.EmailField(verbose_name = 'E-mail')
    created = models.DateTimeField(auto_now_add=True, verbose_name = 'Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name = 'Изменен')
    paid = models.BooleanField(default=False, verbose_name = 'Оплачен')
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
 
    def __str__(self):
        return 'Order {}'.format(self.id)
 
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
 
 
class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', verbose_name = 'Заказ')
    game = models.ForeignKey(Game, related_name='order_items', verbose_name = 'Игра')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name = 'Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name = 'Количество')
 
    def __str__(self):
        return '{}'.format(self.id)
 
    def get_cost(self):
        return self.price * self.quantity
    class Meta:
        verbose_name = 'Предмет заказа'
        verbose_name_plural = 'Предметы заказа'
 

orders/forms.py
from django import forms
 
from .models import Order
 
 
class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        
        fields = ['first_name', 'last_name', 'email']
 
 

orders/views.py
from cart.cart import Cart
from django.shortcuts import render
 
from .forms import OrderCreateForm
from .models import OrderItem, Order
from app.models import Game
 
 
# Create your views here.
 
 
def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order=form.save(commit=False)
            order.nickname=request.user
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, game=item['game'],
                                         price=item['price'],
                                         quantity=item['quantity'])
                # clear the cart
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'title':'Оформление заказа','order': order})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html',
                  {'title':'Оформление заказа', 'cart': cart, 'form': form})

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Мы маленькаая компания, занимающаяся продажей игр. <br />На нашем сатйе вы можете преобрести игры таких игровых площадок как Steam, Gog, Epic Gаme Store.</p>

{% endblock %}

app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}
<h2>{{ title }}</h2> <br />

{% for post in posts %}
<hr />
<div class=" ">
    <h2> {{post.title}}</h2>
    <h4> {{post.posted}}</h4>
    <p> {{post.description}}</p>
    <p><a href="{% url 'blogpost' parametr=post.id %}"> Читать далее </a> </p>
</div>
{% endfor %}
{% endblock %}

app/templates/app/blogpost.html
{% extends "app/layout.html" %}
{% block content %}

<h2> {{post_1.title}} </h2>
<p> {{post_1.content|linebreaksbr}} </p>  


{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
   <img src="{{ post_1.image.url }}" alt="Картинка" widht="450" height="350"/>
{% endif %}
<p><a href="{% url 'blog' %} ">Назад</a></p>
{% if user.is_authenticated  %}
    <h3>Добавить комментарий</h3>
    <form method="POST">{% csrf_token %}
    <div>
        {{form.as_p}}
        <button type ="submit" class="save btn btn-default">Отправить комментарий </button>
    </div>
    </form>

{% else %} 
    <h3> Для добавления комментария необходимо авторизоваться</h3>
{% endif %}
{% for comment in comments %}
<hr />
<h6>{{comment.date}}</h6>
<h5>{{comment.author}}</h5>
<p>{{comment.text|linebreaksbr }}</p>
{% endfor %}

{% endblock %}

app/templates/app/edit_order.html
{% extends "app/layout.html" %}

{% block content %}
<br />
<form method="POST">
        {% csrf_token %}
        <p>
            <label>Заказ оплачен (Только: True или False) </label><br>
            <input type="text" name="paid" value="{{order.paid}}" />
        </p>
       
        <input type="submit" value="Сохранить" >
    </form>

{% endblock %}

app/templates/app/empty.html
{% extends "app/layout.html" %}

{% block content %}



<h1>Список ваших заказов - пуст</h1>

{% endblock %}

app/templates/app/game_detail.html
{% extends "app/layout.html" %}
{% load static %}
 
{% block title %}
  {% if category %}{{ category.title }}{% else %}Игры{% endif %}
{% endblock %}
 
{% block content %}
    <div class="game-detail">
    <img style="width:600px" src="{% if game.image %}{{ game.image.url }}{% else %}{% static 'app/img/no_image.png' %}{% endif %}">
    <h1>{{ game.name }}</h1>
    <h2><a href="{{ game.category.get_absolute_url }}">{{ game.category }}</a></h2>
    <p class="price">{{ game.price }} руб.</p>
    <form action="{% url "cart:cart_add" game.id %}" method="post">
        {{ cart_game_form }}
        {% csrf_token %}
        <input type="submit" value="Добавить в корзину">
</form>
      {{ game.description|linebreaks }}
  </div>
{% endblock %}

app/templates/app/game_list.html
{% extends "app/layout.html" %}
{% load static %}
 
{% block title %}
    {% if category %}{{ category.name }}{% else %}Игры{% endif %}
{% endblock %}
 
{% block content %}
    <div id="sidebar">
        <h3>Жанры</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "app:game_list" %}">Все</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
        <h3>Игры</h3>
    <div id="main" class="game-list" >
        <h3>{% if category %}{{ category.name }}{% else %}
            {% endif %}</h3>
        <div style="display: flex; flex-wrap:wrap; flex-direction:row;">
        {% for game in games %}
            <div class="item" style="margin:0px 10px;">
                <a href="{{ game.get_absolute_url }}">
                    <img style="width:300px" src="
                            {% if game.image %}{{ game.image.url }}{% else %}{% static "shop/img/no_image.png" %}{% endif %}">
                    
                    
                </a>
                <br></br>
                <a href="{{ game.get_absolute_url }}">{{ game.name }}</a><br>
               <h4>{{ game.price }} руб.</h4> 
            </div>
        {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="3000" style="width:700px;
  margin:0 auto;">

    <ol class="carousel-indicators">

        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>

        <li data-target="#myCarousel" data-slide-to="1"></li>

        <li data-target="#myCarousel" data-slide-to="2"></li>

        

    </ol>

    <div class="carousel-inner" role="listbox">

        <div class="item active" style="width:700px;">

           <a href ="16/cyberpunk2077/" target="_blank"> <img src="{% static 'app/content/banner1.jpg'%} " alt="Первый слайд" class="img-responsive" /></a>

            

        </div>

        <div class="item" style="width:700px";>

           <a href ="/4/witcher2/" target="_blank"> <img src="{% static 'app/content/banner2.jpg'%}" alt="Второй слайд"  class="img-responsive" /> </a>

          

        </div>

        <div class="item" style="width:700px";>

           <a href ="/1/witcher-3-wild-hunt/" target="_blank"> <img src=" {% static 'app/content/banner3.jpg'%} " alt="Третий слайд"  class="img-responsive" /> </a>

   

        </div>

    </div>

    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">

        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>

        <span class="sr-only">Предыдущее</span>

    </a>

    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">

        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>

        <span class="sr-only">Следующее</span>

    </a>

</div>


<div>
	<h3>О магазине</h3>
	<p>В нашем интернет-магазине вы сможете гарантированно приобрести ключи к играм от Steam, Uplay, Battle.net и прочих популярных игровых платформ. Наш магазин делает все для того, чтобы ваши покупки проходили быстро, с максимальным удобством и безопасностью, а цены оставались максимально доступными.</p>
	<hr></hr>
	</div>

	<h3>Наши преимущества</h3>
	<ul class="homelist">
	<li>Низкие цены (или нет)</li>
	<li>Мгновенные операции</li>
	<li>Широкий выбор</li>
	</ul>
	<br></br>
	<p>Здесь могла быть ваша реклама</p>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - TheWeachShop</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"> <img src="{% static 'app/content/3.png' %}" alt="logo" /> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li><a href="{% url 'blog' %}">Новости</a></li>
                    
                    <li><a href="{% url 'app:game_list' %}">Магазин</a></li>
                    {% if not user.is_staff %}
                    <li><a href="{% url 'about' %}">О сайте</a></li>
                    {% endif %}
                    {% if  user.is_authenticated %}
                    {% if not user.is_staff %}
                    <li><a href="{% url 'app:my_orders' %}">Ваши заказы</a></li>
                    {% endif %}
                    {% endif %}
                    {% if not user.is_staff %}
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    {% endif %}
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавить новость</a></li>
                    {% endif %}
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newgame' %}">Добавить товар</a></li>
                    {% endif %}
                    {% if user.is_superuser %}
                    <li><a href="{% url 'users' %}">Пользователи</a></li>
                    {% endif %}
                    {% if user.is_staff %}
                    {% if not user.is_superuser %}
                    <li><a href="{% url 'orders' %}">Заказы</a></li>
                    {% endif %}
                    {% endif %}
                    {% if not user.is_authenticated %}
                        <<li><a href="{% url 'registration' %}">Регистрация</a></li>
                    {% endif %}
                    {% if not user.is_staff %}
                    <li><div class="cart">
                                {% with total_items=cart|length %}
                                {% if cart|length > 0 %}
                                    Ваша корзина:
                                <a href="{% url "cart:cart_detail" %}">
                                {{ total_items }} товаров{{ total_items|pluralize }},
                                {{ cart.get_total_price }} руб.
                                </a>
                               {% else %}
                                    Ваша корзина пуста.
                                    {% endif %}
                               {% endwith %}</div></li>
                    {% endif %}
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer style="bottom:0; position:relative">
            <p>&copy; {{ year }} TheWeachShop</p>
        </footer>
    </div>

    
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте учетную запись данного сайта, чтобы войти.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильный пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/my_orders.html
{% extends "app/layout.html" %}

{% block content %}
<h2>Ваши заказы</h2> <br />

{% for item in game_ordered %}
<hr />
<div class=" ">
    <h2> Заказ №{{item.order_id}}</h2>
    <h4> Название игры: {{item.game}}</h4>
    <h4> Цена: {{item.price}} руб.</h4>
    <h4> Количество: {{item.quantity}}</h4>
    
   
</div>

{% endfor %}

{% endblock %}

app/templates/app/newgame.html
{% extends "app/layout.html" %}
{% block content %}


<h3>Добавить товар</h3>
<form method="POST" enctype="multipart/form-data"> {% csrf_token %} 
<div>
    {{gameform.as_p}}
    <button type="submit" class="save btn btn-default"> Сохранить товар </button>
</div>    
</form>

{% endblock %}

app/templates/app/orders.html
{% extends "app/layout.html" %}
{% block content %}
<br />
<h2>Заказы</h2>
    <table>
        <thead><th>Id</th><th>Название игры</th><th>Цена</th>><th>Дата создания</th><th>Количество</th><th>Фамилия покупателя</th><th>E-mail</th><th>Заказ оплачен</th></thead>
        {% for g  in game_ordered  %}
        
        <tr style="color:red; text-align:center; text-shadow:black 0px 0px 3px;">
            <td>{{ g.order_id }}</td>
            <td>{{ g.game }}</td>
            <td>{{ g.price }}</td>
            <td>{{ g.created }}</td>
            <td>{{ g.quantity }}</td>
            <td>{{ g.first_name }}</td>
            <td>{{ g.email }}</td>
            <td>{{ g.paid }}</td>
            <td><a href="{% url 'edit_order' id=g.order_id %}">Настройка статуса заказа</a>
        </tr>
           
        {% endfor %}
        
    </table>
    
{% endblock %}

app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Регистрация</h2>
    <form method="POST" > {% csrf_token %}
        <div>
            {{ regform.as_p}}

            <button type="submit" class-"save btn btn-default">
                Зарегистрировать
            </button>
        </div>    
    </form>
{% endblock %}